# condiciones en numpy
array>num: esto develve dependiendo de los valores del array False y True. donde num es un numero. Cundo ponemos su resultado para la indexación del array se visualizará los valores del array en donde existe True.

Si queremos hacer condición con & siempres tenemos que poner los parentecis a los operandons ya que de lo contrario da error
array[(array>5) & (array<9)]


In [19]:
import numpy as np

In [20]:
array=np.linspace(start=1, stop=10, num=10, dtype=np.int8)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [21]:
index_cond=array>5
index_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [22]:
array[index_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [23]:
array[(array>5) & (array<9)]

array([6, 7, 8], dtype=int8)

In [24]:
array[(array>5)]=99

In [25]:
array

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [26]:
array[array==99]

array([99, 99, 99, 99, 99], dtype=int8)