# copy

Cuando tomamos un trozo del array sin copiar, ese trozo sigue referenciando al array original por tanto si ocurren modificaciones para los valores del trozo el array original tambien recibira esas modificaciones.

- Función np.copy(a=array): permite copiar un array
- Mentodo array.copy(): permite copiar el array.



In [1]:
import numpy as np

In [3]:
array=np.arange(start=0, stop=10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
trozo_array=array[:6]
trozo_array

array([0, 1, 2, 3, 4, 5])

In [7]:
trozo_array[:]=0
trozo_array

array([0, 0, 0, 0, 0, 0])

In [9]:
array

array([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])

In [11]:
array_copy=array.copy()
array_copy

array([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])

In [13]:
array_copy[:]=100
array_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [14]:
array

array([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])