# CREANDO ARRAYS DIRECTO CON NUMPY
Tenemos un numero amplio de posibilidades para crear array directamente desde numpy y ademas de ello es más eficiente\
\
arange de numpy funciona casi similar a range de python la diferencia es que el primero crea arrays directamente.

- range(start, stop, step)
- np.arange(start, stop, step)

\
np.zeros((dimension)): permite crear arrays de ceros de culquier dimensión. La dimension se especifica dentro de una tupla en su forma dimensional\

np.ones((dimension)): Permite crear arrays de unos de cualquier dimension. Es casi igual a np.zeros((dimension))\


np.linspace(start, stop, numero_ejemplares): La función numpy.linspace genera un array NumPy formado por n números equiespaciados entre dos dados. numpy.linspace(valor-inicial, valor-final, número de valores)\

np.logspace(start,stop,numero_datos) # genera datos espacidas en una escala logaritmica\

np.eye(forma de la matriz cuadaratica) devuelve una matriz identidad con la forma especificada\

np.random.rand(dimension): La dimension=d0,d1,d2,...,dn. genera un numero aleatorio entre 0 y 1. genera valores aleatorios en una forma dada\

np.random.randint(low, high, size) = np.random.randint(bajo, alto, tamaño): Genera array desde cero dimensiones hasta n dimensional dependiendo que tamaño se especifica y sus elementos son aleatorias especificando low y high(bajo y alto)




In [35]:
import numpy as np


In [36]:
# Range es de python y nos permite crear crear listas de manera con el list(range())
# Range es inefiente. ya que eso mismo podemos acerlo con un funcion de numpy
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
# arange es una función de numpy que nos ayuda a crear arrays
# arange nos crea desde posición 0 a 10 en el ejemplo siguiente
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# arange(start, stop, step)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
# np.zeros((dimension))
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
# np.ones((dimension))
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
np.ones((3,4), dtype=np.int8)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [52]:
# np.linspace(start, stop, numero_ejemplares) #genera ejemplares equiespaciadas entre dos datos
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [141]:
#np.logspace(start,stop,numero_datos) # genera datos espacidas en una escala logaritmica
np.logspace(start=0, stop=10,num=10)

array([1.00000000e+00, 1.29154967e+01, 1.66810054e+02, 2.15443469e+03,
       2.78255940e+04, 3.59381366e+05, 4.64158883e+06, 5.99484250e+07,
       7.74263683e+08, 1.00000000e+10])

In [140]:
# np.eye(forma de la matriz cuadaratica) devuelve una matriz identidad con la forma especificada
np.eye(N=4, dtype=np.int32)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [76]:
# np.random.rand(dimension): genera un numero aleatorio entre 0 y 1. genera valores aleatorios en una forma dada
np.random.rand()

0.2271145606665529

In [89]:
np.random.rand(4)

array([0.43494993, 0.79228916, 0.88211302, 0.08215702])

In [134]:
# np.random.rand(dimensicon)        dimension=d0,d1,d2,...,dn
n=np.random.rand(4,4,2)
print(n)

[[[0.16815971 0.48686914]
  [0.87274381 0.01220204]
  [0.57522138 0.30478926]
  [0.43775367 0.34620289]]

 [[0.30164162 0.4031228 ]
  [0.5139801  0.63391819]
  [0.10181979 0.25935362]
  [0.49659455 0.69553402]]

 [[0.85473694 0.89509712]
  [0.53783363 0.81799676]
  [0.60786293 0.60339614]
  [0.6543899  0.04306897]]

 [[0.94949054 0.63355121]
  [0.60178738 0.68344158]
  [0.63803109 0.82212713]
  [0.53228157 0.34257552]]]


In [131]:
# np.random.randint(low, high, size) = np.random.randint(alto, bajo, tamaño)
np.random.randint(low=1,high=15)

12

In [144]:
np.random.randint(low=1,high=15 , size=(3,3), dtype=np.int32)

array([[ 6, 13,  4],
       [13,  4, 10],
       [ 8, 11,  1]], dtype=int32)

In [145]:
np.random.randint(low=1, high=5, size=(3,3), dtype=np.int64)

array([[3, 1, 3],
       [3, 4, 4],
       [3, 1, 1]])