# DIMENSIONES
Siempre necesitamso saber con que dimension estamos trabajando con el fin de acceder a los tensores
## Dimensiones de los datos
- Scalar: Cuando hablamos de un numero en especifico puede ser entero ...1,2,3... y flotante, etc. Ose cuando tiene dimensión 0 ese es un scalar
- Vector: Es cuando estamos hablando de una lista, array, que está conformado por varios numeros. El vector se caracteriza por tener una sola dimensión
- Matrix: Es un colección de numeros de dimension 2. Amenudo son tablas que tienen filas y columnas.
- dim 3: tensor. Es una matrix de 3 dimensiones
- dim 4: Matrix 4 dimensiones
- dim n: A las matrices de n dimensiones se les conoce como Tensor

In [2]:
import numpy as np

In [6]:
# Definiendo un scalar
scalar=np.array(42)
print(scalar)
scalar.ndim # scalar tiene dimension 0

42


0

In [10]:
# Definiendo un vector
vector=np.array([1,2,3])
print(vector)
vector.ndim #El vector tiene dimension 1

[1 2 3]


1

In [15]:
# definiendo una matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6]]
                  )
print(matrix)
matrix.ndim # La matrix tiene dimension 2


[[1 2 3]
 [4 5 6]]


2

In [19]:
# definiendo tensor que son las matrices que tienen 3 dimension para arriba
tensor3 = np.array([[[1, 2, 3],
                      [4, 5, 6]],
                     [[3, 2, 4],
                      [5, 4, 5]],
                     [[6, 7, 8],
                      [9, 6, 8]]
                     ])

print(tensor3)
tensor3.ndim # El tensor de 3 dimensiones


[[[1 2 3]
  [4 5 6]]

 [[3 2 4]
  [5 4 5]]

 [[6 7 8]
  [9 6 8]]]


3

## Agregar o eleminar dimensiones

> Con el parametro ndmin del array() se puede definir el numero de dimensiones que tendra el array

> La función expand_dims() del modulo numpy expande la dimension de un array y es necesario poner el eje(axis) de expansion

> La función squeeze() de modulo numpy conprime al numero de dimensiones correcto que no se esten usando

In [23]:
vector=np.array([1,2,3], ndmin=10) # ndmin=10, definimos la dimension al momento de crear el array
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [27]:
expand=np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [31]:
print(vector, vector.ndim)
vector_2=np.squeeze(vector) # squeeze conprime al numero de dimensiones correcto que no se esten usando
print(vector_2, vector_2.ndim)


[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
