# FUNCIONES PRINCIPALES DE NUMPY

- El metodo max(axis=0): devuelve el dato más alto de un array
- El metodo argmax(axis=1): devuelve el indice del valor máximo en el array
- El metodo min(axis=0): devuelve el valor minimo de un array
- El metodo argmin(axis=0): devuelve el indice del valor minimo en el array
- El metodo ptp(axis=0), podemos obtener el valor de peek-to-peek que es (máximo-mínimo) a lo largo del eje de la matriz dada. 

- La funcion np.percentile(a=array, q=50): El percentil es una medida estadística de posición, que divide la distribución ordenada de los datos en cien partes iguales. con q=50 inidicamos que queremos saber el percentil 50

- La funcion np.sort(a=array): Permite ordenar el array de menor a mayor
- La función np.median(a=array): Es el percentil 50 o simplemente es el vajor que se encuentra en la mitad del array ordenada.
- La funcion np.var(a=array): calcula la varianza del array
- la funcion np.std(a=array): calcula la desviación estandar del array. la desviación estandar es la raíz cuadrada de la varianza.
- La funcion np.mean(a=array): calcula la media de un array. tambien se puede especificar con los axis
- La funcion np.concatenate((a,b)): concatena dos array a y b
- El metodo T: realiza la transpuesta de un array


In [1]:
import numpy as np

In [3]:

array=np.random.randint(low=1, high=20, size=(10))

In [11]:
matrix=array.reshape(2,5)
matrix

array([[13, 17, 14, 12, 19],
       [ 3, 10,  6, 11, 12]])

In [10]:
matrix.ndim

2

In [16]:
array.max(axis=0)

19

In [19]:
matrix

array([[13, 17, 14, 12, 19],
       [ 3, 10,  6, 11, 12]])

In [21]:
matrix.max(axis=0)

array([13, 17, 14, 12, 19])

In [22]:
array.argmax(axis=0)

4

In [23]:
array

array([13, 17, 14, 12, 19,  3, 10,  6, 11, 12])

In [26]:
array.min(axis=0)

3

In [28]:
matrix

array([[13, 17, 14, 12, 19],
       [ 3, 10,  6, 11, 12]])

In [31]:
matrix.min(axis=1)

array([12,  3])

In [33]:
matrix.argmin(axis=1)

array([3, 0])

In [35]:
array

array([13, 17, 14, 12, 19,  3, 10,  6, 11, 12])

In [36]:
array.ptp(axis=0)

16

In [37]:
matrix


array([[13, 17, 14, 12, 19],
       [ 3, 10,  6, 11, 12]])

In [39]:
matrix.ptp(axis=0)

array([10,  7,  8,  1,  7])

In [42]:
array

array([13, 17, 14, 12, 19,  3, 10,  6, 11, 12])

In [43]:
np.sort(a=array)

array([ 3,  6, 10, 11, 12, 12, 13, 14, 17, 19])

In [41]:
np.median(a=array)

12.0

In [40]:
np.percentile(a=array, q=50)

12.0

In [44]:
np.percentile(a=array, q=100)

19.0

In [45]:
np.var(a=array)

20.009999999999998

In [51]:
a=np.std(a=array)

In [52]:
a**2

20.009999999999994

In [53]:
matrix

array([[13, 17, 14, 12, 19],
       [ 3, 10,  6, 11, 12]])

In [63]:
np.var(a=matrix, axis=1)

array([ 6.8 , 11.44])

In [64]:
np.std(a=matrix, axis=1)

array([2.60768096, 3.38230691])

In [65]:
np.sort(a=matrix, axis=1)

array([[12, 13, 14, 17, 19],
       [ 3,  6, 10, 11, 12]])

In [66]:
np.median(a=matrix, axis=1)

array([14., 10.])

In [67]:
np.sort(a=matrix, axis=0)

array([[ 3, 10,  6, 11, 12],
       [13, 17, 14, 12, 19]])

In [68]:
np.mean(a=array)

11.7

# Concatenación

In [86]:
a = np.array(object=[[1, 2],
                     [3, 4]])
print(a, "\n",a.shape)


[[1 2]
 [3 4]] 
 (2, 2)


In [148]:
b=np.array(object=[5,6])
print(b, "\n", b.shape)

[5 6] 
 (2,)


In [149]:
b=np.expand_dims(a=b, axis=1)
b

array([[5],
       [6]])

In [150]:
np.concatenate((a,b.T))

array([[1, 2],
       [3, 4],
       [5, 6]])