# Operaciones en numpy
La lista de python no realiza operaciones como debe ser.

```python
import numpy as np
lista=[1,2]
-> [1,2]

lista*2
-> [1, 2, 1, 2]
```

El arrays de numpy si realizan las operaciones matematicas y matriciales como esperamos
```python
array=np.arange(start=0, stop=10)
arrayc=array.copy()
arrayc
-> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arrayc*2
-> array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])
```

En fin podemos hacer operaciones con los array de numpy. + , *, /, etc


El producto punto de matrices puedes relizar con el metodo np.matmul(matrix, matrix2)
tambiene s posible realizar con @ y tiene el mismo resultado
```python
np.matmul(matrix, matrixc.T)
-> array([[ 30,  80],
          [ 80, 255]])

matrix@matrixc.T
-> array([[ 30,  80],
          [ 80, 255]])
```


In [1]:
import numpy as np

In [2]:
lista=[1,2]
lista

[1, 2]

In [3]:
lista*2

[1, 2, 1, 2]

In [4]:
array=np.arange(start=0, stop=10)
arrayc=array.copy()
arrayc

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arrayc*2


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arrayc+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
arrayc/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [9]:
arrayc**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
arrayc+arrayc

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
arrayc*arrayc

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [15]:
matrix=arrayc.reshape(2,5)
matrix


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
matrixc=matrix.copy()
matrixc

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
matrixc+matrix

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [19]:
matrix*matrixc

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [20]:
np.matmul(matrix, matrixc.T)

array([[ 30,  80],
       [ 80, 255]])

In [21]:
matrix@matrixc.T

array([[ 30,  80],
       [ 80, 255]])