## SHAPE AND RESHAPE
SHAPE=FORMA
RESHAPE=reestablecer forma

> La propieda shape para los objetos de tipo array nuestra la forma del array

> Objetoarray.reshape():  reshape es un metodo para cambiar la forma de un array

> Función reshape permite casi los mismo que el metodo reshape


> realizar reshape como lo haría en el lenguaje C. realiza tomando filas
np.reshape(a=array2d, newshape=(2,3), order="C")

> realiza reshape como el lenguaje fortran es por ello el F. Realiza el reshape tomando columnas
np.reshape(a=array2d, newshape=(2,3), order="F")

> Realiza al mejor optimización de almacenamiento de tu sistema con order="A". Realizo en este caso como en el lenguaje C
np.reshape(a=array2d, newshape=(2,3), order="A")

Es recomendable hacer el reshape con la forma de lenguaje C. Ya que python ha sido construido con C


**RETO**
- Crear un array de cualquier dimensión y cambiar sus dimensiones.
- Intenta cambiar el array de forma que no respete la estructura original

In [30]:
import numpy as np

In [31]:
array2d=np.random.randint(low=1,high=10,size=(3,2))

array2d

array([[5, 7],
       [6, 7],
       [7, 4]])

In [32]:
# la propieda shape para los objetos de tipo array nuestra la forma del array en (y,x)
array2d.shape

(3, 2)

In [33]:
array2d

array([[5, 7],
       [6, 7],
       [7, 4]])

In [42]:
# objetoarray.reshape():  reshape es un metodo para cambiar la forma de un array
array2d.reshape(1,6)

array([[5, 7, 6, 7, 7, 4]])

In [35]:
array2d.reshape(2,3)

array([[5, 7, 6],
       [7, 7, 4]])

In [36]:
# Función reshape permite casi los mismo que el metodo reshape
np.reshape(a=array2d, newshape=(2,3))

array([[5, 7, 6],
       [7, 7, 4]])

In [37]:
array2d

array([[5, 7],
       [6, 7],
       [7, 4]])

In [38]:
# realizar reshape como lo haría en el lenguaje C. realiza tomando filas
np.reshape(a=array2d, newshape=(2,3), order="C")

array([[5, 7, 6],
       [7, 7, 4]])

In [39]:
# realiza reshape como el lenguaje fortran es por ello el F. Realiza el reshape tomando columnas
np.reshape(a=array2d, newshape=(2,3), order="F")

array([[5, 7, 7],
       [6, 7, 4]])

In [40]:
# Realiza al mejor optimización de almacenamiento de tu sistema con order="A". Realizo en este caso como en el lenguaje C
np.reshape(a=array2d, newshape=(2,3), order="A")

array([[5, 7, 6],
       [7, 7, 4]])